name: native_ble_impl
description: A example usage for the l2cap_ble package.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  flutter_reactive_ble: ^5.1.1
  intl: ^0.18.1
  flutter_riverpod: ^2.3.6
  meta: ^1.9.1
  flutter_hooks: ^0.18.6
  l2cap_ble: 
    path: ../l2cap_ble

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
