name: l2cap_ble
description: A new Flutter plugin project.
repository: https://github.com/appsfactorygmbh/flutter-l2cap
version: 0.0.1
homepage: https://appsfactory.de

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: de.appsfactory.l2cap_ble
        pluginClass: L2capBlePlugin
      ios:
        pluginClass: L2capBlePlugin